### ISSUE TITLE
Deploy scripts 

### ISSUE THREAD

**Issue by LiorI9** [LiorI9/frenziQMVP#36]
for Firebase and GCP
for simple deploy fro git (local)

**Comment by camillarhodes** [comment]
what should "deploy from git" do? pull from master and create apk?

**Comment by LiorI9** [comment]
This only for the server side...
Firebase func and GCP code

**Comment by camillarhodes** [comment]
so it is only 1 script that does:
1. pull master form github
2. deploy firebase func and GCP (with the code pulled from github)

?

**Comment by LiorI9** [comment]
Yup
5 min of work
But we agreed that all the issues will be managed in GitHub ;-9
